import os
import re
import json
import datetime
from decimal import Decimal
import psycopg2


class DecimalEncoder(json.JSONEncoder):
    """Custom JSON encoder to safely handle PostgreSQL Decimal and DateTime data types."""

    def default(self, obj):
        if isinstance(obj, Decimal):
            return float(obj)
        if isinstance(obj, (datetime.datetime, datetime.date)):
            return obj.isoformat()
        return super(DecimalEncoder, self).default(obj)


class DatabaseManager:
    """Manages high-privilege configuration, table schemas, and permissions structural work."""

    def __init__(self):
        self.host = os.getenv("DB_HOST")
        self.db_name = os.getenv("DB_NAME")
        self.admin_user = os.getenv("DB_USER")
        self.admin_password = os.getenv("DB_PASSWORD")
        self.schema = os.getenv("TARGET_SCHEMA", "public_read_only")
        self.reader_user = os.getenv("LLM_READER_USER", "llm_reader")
        self.reader_password = os.getenv("LLM_READER_PASSWORD", "readonlypassword")

    def get_admin_connection(self):
        return psycopg2.connect(
            host=self.host,
            database=self.db_name,
            user=self.admin_user,
            password=self.admin_password,
        )

    def initialize_environment(self):
        """Creates custom schemas, activates fuzzy matching, and loads default data from data/data.sql."""
        sql_file_path = "data/data.sql"
        try:
            # 1. Read the schema and structural scripts from the target file
            if not os.path.exists(sql_file_path):
                raise FileNotFoundError(
                    f"The structural script was not found at: '{sql_file_path}'"
                )

            with open(sql_file_path, "r", encoding="utf-8") as f:
                sql_script = f.read()

            with self.get_admin_connection() as conn:
                with conn.cursor() as cursor:
                    # 2. Execute the entire SQL script string dynamically against the database
                    cursor.execute(sql_script)

                    # 3. Set the password
                    cursor.execute(
                        f"ALTER ROLE {self.reader_user} WITH PASSWORD '{self.reader_password}';"
                    )

                    conn.commit()
            print(
                f"Database initialized with external data file matching schema: '{self.schema}'"
            )
        except Exception as e:
            print(f"Database initialization lifecycle failure: {e}")


class DatabaseTool:
    """Safely validates, cleans, and routes read-only queries through restricted user logins."""

    def __init__(self):
        self.host = os.getenv("DB_HOST")
        self.db_name = os.getenv("DB_NAME")
        self.user = os.getenv("LLM_READER_USER", "llm_reader")
        self.password = os.getenv("LLM_READER_PASSWORD", "readonlypassword")
        self.forbidden_keywords = [
            "drop",
            "delete",
            "truncate",
            "update",
            "insert",
            "alter",
            "grant",
        ]

        raw_tables = os.getenv("ALLOWED_TABLES", "products,orders")
        self.allowed_tables = [t.strip() for t in raw_tables.split(",") if t.strip()]

        # we want deterministic answers - todo this does not really work
        try:
            self.seed = int(os.getenv("LLM_SEED", "0"))
        except ValueError:
            print("[WARN] LLM_SEED in .env is not a valid integer. Defaulting to 0.")
            self.seed = 0

    def get_connection(self):
        return psycopg2.connect(
            host=self.host,
            database=self.db_name,
            user=self.user,
            password=self.password,
        )

    def _sanitize_query(self, sql_query: str) -> str:
        cleaned = sql_query.strip()
        has_semicolon = cleaned.endswith(";")
        if has_semicolon:
            cleaned = cleaned[:-1]

        group_by_id_pattern = r"(?i)\s+group\s+by\s+([a-zA-Z0-9_\.]+)?\b(id)\b"
        if re.search(group_by_id_pattern, cleaned):
            print(
                f"[SQL SANITIZER] Intercepted primary key grouping clause inside: '{sql_query}'"
            )
            cleaned = re.sub(group_by_id_pattern, "", cleaned)
            select_id_comma_pattern = r"(?i)select\s+(\w+\.)?id\s*,\s*"
            cleaned = re.sub(select_id_comma_pattern, "SELECT ", cleaned)

        if has_semicolon:
            cleaned += ";"
        return cleaned

    def execute_read_query_raw(self, sql_query: str) -> list:
        """Executes query and returns a clean, native Python list object with serialized decimals."""
        sql_query = self._sanitize_query(sql_query)
        print(f"[TOOL EXECUTION] Processing query context: {sql_query}")

        if any(keyword in sql_query.lower() for keyword in self.forbidden_keywords):
            raise PermissionError(
                "Security Error: Prohibited operational structure string generated by LLM."
            )

        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(sql_query)
                columns = [desc[0] for desc in cursor.description]
                results = cursor.fetchall()

                raw_records = [dict(zip(columns, row)) for row in results]
                json_str = json.dumps(raw_records, cls=DecimalEncoder)
                return json.loads(json_str)


class SchemaDiscoverer:
    """Queries system catalog records at runtime to auto-generate documentation for the LLM."""

    def __init__(self):
        self.db_tool = DatabaseTool()
        self.target_schema = os.getenv("TARGET_SCHEMA", "public_read_only")

    def get_active_schema_documentation(self) -> str:
        query = f"""
            SELECT table_name, column_name, data_type 
            FROM information_schema.columns 
            WHERE table_schema = '{self.target_schema}'
            ORDER BY table_name, ordinal_position;
        """
        try:
            with self.db_tool.get_connection() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(query)
                    rows = cursor.fetchall()

            if not rows:
                return "Schema Status Notice: No accessible structural tables found."

            schema_map = {}
            for table, column, d_type in rows:
                if table not in schema_map:
                    schema_map[table] = []
                schema_map[table].append(f"{column} ({d_type})")

            doc_lines = ["Available Database Tables and Structural Columns:"]
            for table_name, columns in schema_map.items():
                col_string = ", ".join(columns)
                doc_lines.append(
                    f"- Table: {self.target_schema}.{table_name} -> Columns: [{col_string}]"
                )

            return "\n".join(doc_lines)

        except Exception as e:
            print(
                f"[SCHEMA DISCOVERER ERROR] Could not extract live documentation data: {e}"
            )
            # Fix column headers to perfectly mirror your live schema tables
            return f"- Table: {self.target_schema}.products -> Columns: [id (integer), product_name (character varying), product_price (numeric), stock_volume (integer)]"
